export default {
  START_GAME: 'START_GAME',
  STOP_GAME: 'STOP_GAME',
  BLOW_UP: 'BLOW_UP',

  TICK_GAME: 'TICK_GAME',

  GENERATE_FIELD: 'GENERATE_FIELD',

  CHANGE_SETTINGS: 'CHANGE_SETTINGS',
  OPEN_SETTINGS: 'OPEN_SETTINGS',
  CLOSE_SETTINGS: 'CLOSE_SETTINGS',

  OPEN_CELL: 'OPEN_CELL',
  FLAG_CELL: 'FLAG_CELL',
  CHECK_MINES_AROUND: 'CHECK_MINES_AROUND',
};